USE ЛР6

SELECT	AUDITORIUM.AUDITORIUM_TYPE,
		min(AUDITORIUM_CAPACITY) [Мин. вмест.],
		max(AUDITORIUM_CAPACITY) [Макс. вмест.],
		avg(AUDITORIUM_CAPACITY) [Средняя вмест.],
		count (*)					[Кол-во аудиторий],
		sum(AUDITORIUM_CAPACITY) [Суммарное кол-во]
FROM AUDITORIUM Inner Join AUDITORIUM_TYPE
	On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
		GROUP BY AUDITORIUM.AUDITORIUM_TYPE;
