USE ЛР6

SELECT	FACULTY.FACULTY_NAME [Факультет],
		GROUPS.PROFESSION [Специальность],
		STUDENT.IDGROUP [Номер группы],
		round(avg(cast(PROGRESS.NOTE AS float(4))), 2) [Средний балл]
	FROM FACULTY INNER JOIN GROUPS 
	ON FACULTY.FACULTY = GROUPS.FACULTY
	inner join STUDENT
	ON STUDENT.IDGROUP = GROUPS.IDGROUP
	inner join PROGRESS
	ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		GROUP BY	FACULTY.FACULTY_NAME, 
					GROUPS.PROFESSION,
					STUDENT.IDGROUP
