USE ЛР6

SELECT	GROUPS.FACULTY [Факультет],
		GROUPS.PROFESSION [Специальность],
		PROGRESS.SUBJECT [Предмет],
		round(avg(cast(PROGRESS.NOTE AS float(4))), 2) [Средняя отметка]
	FROM GROUPS, STUDENT, PROFESSION, PROGRESS
	WHERE GROUPS.FACULTY in ('ТОВ')
	GROUP BY ROLLUP (GROUPS.FACULTY,
			 GROUPS.PROFESSION, 
			 PROGRESS.SUBJECT);
