USE À–6

SELECT 
	FACULTY.FACULTY,
	GROUPS.PROFESSION,
	round(avg(cast(PROGRESS.NOTE AS float(4))), 2) as AVG_NOTE
FROM GROUPS 
	inner join FACULTY 
ON FACULTY.FACULTY = GROUPS.FACULTY
	inner join STUDENT
ON STUDENT.IDGROUP = GROUPS.IDGROUP
	inner join PROGRESS
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE FACULTY.FACULTY in ('“Œ¬')
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION
	UNION
SELECT 
	FACULTY.FACULTY,
	GROUPS.PROFESSION,
	round(avg(cast(PROGRESS.NOTE AS float(4))), 2) as AVG_NOTE
FROM GROUPS 
	inner join FACULTY 
ON FACULTY.FACULTY = GROUPS.FACULTY
	inner join STUDENT
ON STUDENT.IDGROUP = GROUPS.IDGROUP
	inner join PROGRESS
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE FACULTY.FACULTY in ('À’‘')
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION
