USE ЛР6

SELECT	PROGRESS.SUBJECT [Предмет],
		PROGRESS.NOTE [Отметка], 
		(SELECT COUNT(*) FROM STUDENT, PROGRESS where PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT ) [Кол-во студентов]
FROM PROGRESS
GROUP BY PROGRESS.NOTE, PROGRESS.SUBJECT
HAVING PROGRESS.NOTE > 6
