USE ЛР6

Select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ИДиП'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
intersect
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ИТ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY