USE ЛР5

SELECT PULPIT_NAME [Кафедра], FACULTY.FACULTY [Факультет]
FROM FACULTY, PULPIT
WHERE FACULTY.FACULTY = PULPIT.FACULTY
AND
FACULTY.FACULTY IN (SELECT FACULTY FROM PROFESSION WHERE (PROFESSION_NAME LIKE '%технология%'
OR PROFESSION_NAME LIKE '%технологии%'))
