USE кп5

SELECT TOP(1)
(SELECT AVG(NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'нюХо')[нюХо],
(SELECT AVG(NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'ад')[ад],
(SELECT AVG(NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT like 'ясад')[ясад]
FROM PROGRESS
