USE ЛР4

SELECT AUDITORIUM.AUDITORIUM AS [Номер аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME AS [Тип Аудитории]
FROM AUDITORIUM , AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
