USE ЛР4

SELECT FACULTY.FACULTY AS [Факультет], PULPIT.PULPIT AS [Кафедра], GROUPS.PROFESSION AS [Специальность],
		SUBJECT_NAME AS [Предмет], STUDENT.NAME AS [Имя студента], PROGRESS.NOTE AS [Оценка],
CASE
	WHEN (PROGRESS.NOTE = 6) THEN 'Шесть'
	WHEN (PROGRESS.NOTE = 7) THEN 'Семь'
	WHEN (PROGRESS.NOTE = 8) THEN 'Восемь'
END [Оценка]



FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
INNER JOIN SUBJECT ON PULPIT.PULPIT = SUBJECT.PULPIT
INNER JOIN PROGRESS ON PROGRESS.SUBJECT = PROGRESS.SUBJECT
WHERE (PROGRESS.NOTE BETWEEN 6 AND 8)

order by FACULTY.FACULTY,PULPIT.PULPIT,STUDENT.NAME, GROUPS.PROFESSION, PROGRESS.NOTE DESC
