USE ËÐ4

SELECT COUNT(*)
FROM PULPIT FULL OUTER JOIN TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE(TEACHER.PULPIT is null)

SELECT COUNT(*)
FROM PULPIT FULL OUTER JOIN TEACHER
ON TEACHER.PULPIT = PULPIT.PULPIT
WHERE(TEACHER.PULPIT is null)
